### ISSUE TITLE
Search Box

### ISSUE THREAD

**Issue by SachinMittal1766** [osBins/chatApp#101]
Search box CSS is not good. @PrimalPimmy I want improve CSS. pls assign it to me.
![Screenshot (761)](https://user-images.githubusercontent.com/82721772/146677469-1df94fde-cda7-44ab-a603-5ebf4d9f1983.png)

**Comment by osBins** [comment]
Absolutely. We can do with a pretty search box. You can get working on it right away. Also, since I haven't been asked to assign this issue (😔😔😔😔😔😔) @PrimalPimmy can you assign the issue to him?
