### ISSUE TITLE
Styling the login/sign up page

### ISSUE THREAD

**Issue by snahashisk** [osBins/chatApp#103]
![signUpPage](https://user-images.githubusercontent.com/77480125/146805298-0226f87d-547a-491f-a1ce-e9a2425e48e9.png)

Implementing a design like this for the Sign Up as well as the Login page.
Please assign me this @PrimalPimmy @osBins

**Comment by PrimalPimmy** [comment]
Alright 👍

**Comment by osBins** [comment]
@snahashisk along with that, can you look into the logout button once again? It looks fine on 80% zoom on a 125% scaled display (1920x1080), but looks fine on normal zoom on a 100% scaled display.
![image](https://user-images.githubusercontent.com/70942982/146929595-007e8702-1969-4189-9fd6-fea572fd244b.png)

**Comment by snahashisk** [comment]
okay I'll fix  that too
