### ISSUE TITLE
fix outlines on searchbox, and other buttons

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#127]
On clicking the search box, the default browser outline is coming which **needs to be removed**.  
![image](https://user-images.githubusercontent.com/70942982/147575160-813b2222-6c3d-485a-befc-30fafb2b9b32.png)  
The same can be observed when the search icon on its left is clicked, when the 'send' button is clicked, and when the logout button is clicked.

**Comment by sushovanb02** [comment]
@osBins wanna work on this
