### ISSUE TITLE
fix image sending bug where image appears on left side even when current user sends it

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#129]
In the newer UI, on sending an image, no matter who sends it, it is being rendered on the left side. Image should be rendered on right side in the message-callout box if current user is sending it and should render on the left normally (also in the message-box) if someone else sends it.  
![image](https://user-images.githubusercontent.com/70942982/147575690-bc4ac2a8-4730-4e6a-8f03-adabdd768d96.png)

**Comment by Shreya-Agrawal-2121** [comment]
I have worked out a solution to fix this bug. Kindly look into it
