### ISSUE TITLE
fix how JavaScript fetches and renders timestamp for messages

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#131]
Currently, the site uses Moment.js to fetch time in the UTC time standard and offsets it by +5:30 to show Indian time. However if anyone uses the chatApp outside of India, it will display time wrongly for them.  
```
let time = moment().utcOffset("+05:30").format('hh:mm A');
```  
Need a fix to either
- display the local system time for message timestamp instead of fetching UTC time and offsetting it by a constant +5:30
- **OR** fetch UTC time and offset it depending on the location of the user to display correct time to them.

**Comment by snahashisk** [comment]
Please assign me this.

**Comment by osBins** [comment]
All yours @snahashisk

**Comment by 0913hung** [comment]
How about using Date.now() to set the timestamp of a message then store as number instead of plain text? The data structure could be more consistent and easy to search by a date range later on. Then on frontend, using toLocaleString() to parse into user's  local time

**Comment by osBins** [comment]
Thank you for your input @0913hung! I was actually wondering the same thing as well. 
@snahashisk can you elaborate on why we went with Moment.js over using the `Date.now()` method?

**Comment by snahashisk** [comment]
https://golb.hplar.ch/2017/01/JavaScript-Date-and-moment-js.html
You can go through this.

My reasons for going with Moment:

- Easier to format date and time (moment.js provides many ways for converting a moment object to a string with the format() function.)
- Lot more functionality (provides many additional get and set functions built-in)
- Presence of validation
- chainable setters 
I hope you got my point. It's just better. 😊

**Comment by osBins** [comment]
That's a great justification for using Moment.js. I hope this answers @0913hung's concern too.

**Comment by osBins** [comment]
Still not resolved @snahashisk, check the deployed version [chatApp](https://chatapp-420.herokuapp.com/). Time is incorrect.  
![image](https://user-images.githubusercontent.com/70942982/147922630-4d41ae32-b196-4579-babd-853a1f32b4e2.png)  
It's currently showing UTC time.
