### ISSUE TITLE
fix word-wrap in long text messages

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#134]
Currently, long text message overflow out of the message box and get cut on the screen. It would be better if there could be a word-wrap to show full long text message instead of cutting it out of the screen  
![image](https://user-images.githubusercontent.com/70942982/147644562-f30ccb5a-97f1-44e0-940c-cc78e3f8b4d8.png)

**Comment by snahashisk** [comment]
Please assign me this

**Comment by osBins** [comment]
Assigned to you @snahashisk
