### ISSUE TITLE
Update UI of Login Page 

### ISSUE THREAD

**Issue by SachinMittal1766** [osBins/chatApp#140]
I think we can modify the UI of the Login page. I am attaching the photos of how the webpage is looking now and how I want to change it. @osBins assign it to me. So that I can start working on it. 
![SIGN_UI](https://user-images.githubusercontent.com/82721772/147664559-884cbbd4-49dc-4bc2-9254-ba4e3091a084.png)
![LOGIN_UI](https://user-images.githubusercontent.com/82721772/147664562-e164c901-d8ea-4544-97f1-a16b54fc4860.png)

**Comment by osBins** [comment]
That looks neat. Go for it @SachinMittal1766!
