### ISSUE TITLE
Type message for OTP verification (forgot password) which users receive in their inbox

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#147]
Currently, mail received looks like this  
![image](https://user-images.githubusercontent.com/70942982/147849606-7594ed36-9405-4686-8b76-62f7547bfc0f.png)  
A more professional message along with subject would look good.

**Comment by Jigyasa-G** [comment]
I would like to work on this, kindly assign it to me

**Comment by osBins** [comment]
All yours @Jigyasa-G
