### ISSUE TITLE
HTML/CSS | Implement an easy-on-eyes design for the chatApp

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#38]
The current chatApp has a harsh colour scheme which is slightly rough on the eyes. The chatApp would look good with a subtle colour scheme (and UI design).

**Comment by vedantiitkgp** [comment]
I will like to work on this

**Comment by osBins** [comment]
Great! I'm assigning this issue to you @vedantiitkgp. I'd recommend you create a Pull Request as soon as you start working on the issue so that your progress can be tracked!

**Comment by aryanploxxx** [comment]
I would Like to work on this issue too.

**Comment by vedantiitkgp** [comment]
@osBins please close #49  and #59  these are both design issues I have to fix
