### ISSUE TITLE
Implement Sign-up/Login system

### ISSUE THREAD

**Issue by PrimalPimmy** [osBins/chatApp#39]
Instead of people randomly a chat room, we need to add a sign up and login system.

**Comment by aman111222** [comment]
I want to work on this issue.

**Comment by osBins** [comment]
Great! Assigning this issue to you @aman111222. Create a pull request, preferably, as soon as you start working on your issue so that we can track your progress.

**Comment by PrimalPimmy** [comment]
Hey @aman111222 , any progress on this?

**Comment by PrimalPimmy** [comment]
We need to implement login/sign-up system asap in a few days... so if you're not able to do this/ or need help, do tell :D

**Comment by aman111222** [comment]
I am not able to decide where to start. Can you please tell me what are the things that need to read for this project? Currently, I'm reading about react, will be able to complete it within a day.

**Comment by PrimalPimmy** [comment]
This project uses Socket.io, expressJS, simple html css. So no react here. For login/sign-up you'll need to know about PR #67 which is about setting up a database, which is necessary for the project.. come ask in our telegram group.

**Comment by ankitgarg1234** [comment]
I would love to work on this issue can you please assign it to me
