### ISSUE TITLE
Design and add a favicon to the website

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#40]
![image](https://user-images.githubusercontent.com/70942982/143768967-75651014-f4da-422b-a83d-a0636321b169.png)
The chatApp tab would look good with a favicon

**Comment by jaiakash** [comment]
I would like to work on adding favicon for project. Please assign this issue.

**Comment by osBins** [comment]
I appreciate your enthusiasm @jaiakash! I've already assigned an issue to you. I'll assign this issue to you after you are done resolving the other issue and given that no one else calls dibs on this one. Thank you for understanding!

**Comment by jaiakash** [comment]
I understand. I will try to finish the previous issue asap.

**Comment by snahashisk** [comment]
I would like to work on it. Please assign me this.

**Comment by PrimalPimmy** [comment]
Done :+1: , do inform us if you face any issues!

**Comment by snahashisk** [comment]
![favivi-01](https://user-images.githubusercontent.com/77480125/143992270-a45762d4-d6f3-4354-879e-8e0036d225b8.png)
I have added this favicon. can I create a pr?

**Comment by snahashisk** [comment]
i have created a pr #58

**Comment by PrimalPimmy** [comment]
Oh I mean comment on the PR, not here, but alright do that for next PR if you make :+1:
