### ISSUE TITLE
Fix being able to send messages without setting a username

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#41]
Currently, users are not forced to set a username before sending a message on the chatapp. 
![image](https://user-images.githubusercontent.com/70942982/143867936-d459744f-1fd5-4792-adf3-19289cdba3df.png)

> Need to fix this and add a feature to force users to set a username before they can send a message.

**Comment by SachinMittal1766** [comment]
I would like to work on the issue. @osBins Pls assign it to me.

**Comment by osBins** [comment]
Awesome! Assigning the issue to you @SachinMittal1766.
