### ISSUE TITLE
Display "<username> is typing..." instead of "A user is typing..."

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#42]
![image](https://user-images.githubusercontent.com/70942982/143868208-63a1e846-ae09-4312-81c8-6bbc7b637723.png)
Show the username when someone is typing instead of the arbitrary "A user is typing..." message on the chatApp

**Comment by james3gh** [comment]
please assign this issue to me

**Comment by osBins** [comment]
Resolved by #50.
