### ISSUE TITLE
Create a database for storing messages

### ISSUE THREAD

**Issue by PrimalPimmy** [osBins/chatApp#43]
Currently, the messages get deleted as soon as the user disconnects. We need to set up a proper database to store all the messages. DMs can be stored later, current focus is to store the current common chat room. Any NoSQL db can be used, like [Cassandra](https://cassandra.apache.org/_/index.html), or any of your choice if it's easier.

**Comment by KryptonANSHU** [comment]
Hey, I can work on this issue using MongoDB

**Comment by ankitgarg1234** [comment]
I Too want to work on this issue
