### ISSUE TITLE
Move the collapsible 'Online' users list to the right and beautify it 

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#44]
Currently, the collapsible 'online' users list is on the top of the chatApp, and all messages are appended under it. The chatApp would look better with the 'online' users list on the right, collapsible or not.
![image](https://user-images.githubusercontent.com/70942982/143868700-debd0e44-a2ff-4049-9731-40a3d971e3d7.png)

**Comment by aryanploxxx** [comment]
I would like to work on the issue.

**Comment by osBins** [comment]
Great! Assigning this issue to you @aryanploxxx.

**Comment by Koda-Pig** [comment]
Hi @osBins, I've fixed this issue, my pull request is here: https://github.com/osBins/chatApp/pull/46

Sorry for not commenting earlier, thought I might as well share what I worked on.
