### ISSUE TITLE
Improve README.md

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#45]
Add a fitting and verbose description of the chatApp to the README.

Issue is only open for first time contributors to GitHub.

**Comment by iamhardikat11** [comment]
I would like to take this Issue of Improving the README.md

**Comment by PrimalPimmy** [comment]
Great, I'm assigning this to you. Also @iamhardikat11 join our telegram channel for further discussion on how you'll work on this, that'd be helpful for communicating, thanks :)

**Comment by iamhardikat11** [comment]
@PrimalPimmy I am unable to join the telegram channel through the link on KWoC Website. Can you help with problem?

**Comment by iamhardikat11** [comment]
@PrimalPimmy I am unable to join the telegram channel through the link on KWoC Website. Can you help with the problem?

**Comment by iamhardikat11** [comment]
Sure. Will Do……

**Comment by jaiakash** [comment]
Hi, @iamhardikat11 are you still working on the issue?
If not, I would like to take this Issue of Improving the README.md

- [ ] Add new screenshots.
- [ ] Improve readability of texts.
- [ ] Add necessary gaps between texts and images.

**Comment by iamhardikat11** [comment]
Yes, I am!

**Comment by SachinMittal1766** [comment]
@PrimalPimmy @osBins I would like to work on it. pls assign it to me.

**Comment by osBins** [comment]
@iamhardikat11 let me know if you're working on this issue by tomorrow. If not, this issue will be assigned to @jaiakash since he asked for an update first.
Thank you for showing interest in improving the README @SachinMittal1766! If the issue isn't taken up by @jaiakash, I'll make sure it is assigned to you.

**Comment by jaiakash** [comment]
Thnx, I would start working on this issue.

**Comment by osBins** [comment]
Great! Assigning this issue to you@jaiakash

**Comment by iamhardikat11** [comment]
Sorry for the late response, I am still working on it.

**Comment by osBins** [comment]
Feel free to find another issue to work on @iamhardikat11! There was no progress on this since 2 weeks and now it has been assigned to @jaiakash. You can work on another existing issue or create one to work on for yourself. Thank you for understanding! :)

**Comment by osBins** [comment]
@SachinMittal1766 would you be interested in working on this now?

**Comment by SachinMittal1766** [comment]
@osBins Yup, I would love to work on it.

**Comment by soumyac19** [comment]
Can I work on this issue?

**Comment by iamhardikat11** [comment]
Can get to work on it.

**Comment by osBins** [comment]
Assigning this issue to @SachinMittal1766 for now.
@soumyac19 Thank you for showing interest in contributing! Since this is being assigned to someone else right now, can you check out other issues to work on? Feel free to create one of your own if there is anything you would like to implement or edit.
@iamhardikat11 I'm afraid this issue cannot be assigned to you again since it has almost been a month with no progress from your side. Again, have a look at the existing issues or create one of your own if you would really like to work on the chatApp. Thank you for understanding!
