### ISSUE TITLE
Improve the send button 

### ISSUE THREAD

**Issue by snahashisk** [osBins/chatApp#48]
I would like to improve the design of the send button. 
![button](https://user-images.githubusercontent.com/77480125/144001573-1d7127b3-3f27-4eee-967b-2e7afa9cea15.JPG)

**Comment by vedantiitkgp** [comment]
I have updated the button in new design

**Comment by vedantiitkgp** [comment]
@osBins this doesn't require different issue it should have been merged in the design issue
