### ISSUE TITLE
Implement personal messaging feature

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#5]

**Comment by aman111222** [comment]
I want to work on this feature.

**Comment by vedantiitkgp** [comment]
I would also like to work on this feature

**Comment by osBins** [comment]
I like your enthusiasm @aman111222 and @vedantiitkgp! I have already assigned an issue each to you and I'd highly appreciate it if you could resolve your assigned issue and then come back to this one if no one else has been assigned to it! Thank you for understanding!

**Comment by cp-Coder** [comment]
Can I work on this issue??

**Comment by osBins** [comment]
Sure thing! Assigning this issue to you @cp-Coder.
