### ISSUE TITLE
improve username, 'Type a message...' input field

### ISSUE THREAD

**Issue by kuldeepsingh0330** [osBins/chatApp#52]
![3](https://user-images.githubusercontent.com/95225751/144748601-71c5ae14-a9a7-4715-afd9-f955f5cea4bd.png)

like this.......

**Comment by osBins** [comment]
@kuldeepsingh0330, there's someone already working on the send button. Could you center the username placeholder and keep the 'Type a message...' placeholder aligned to the left. Open a Pull Request when you're done with the changes and I'll merge it.

**Comment by kuldeepsingh0330** [comment]
Okk

**Comment by vedantiitkgp** [comment]
I have corrected this in design
