### ISSUE TITLE
Adding a feature to "edit/delete" a message 

### ISSUE THREAD

**Issue by ggggg-15** [osBins/chatApp#56]
The chat app can have a feature to edit or delete an already sent message, in case the user notices a mistake after sending the message. I am interested to contribute here.

**Comment by shivprime94** [comment]
Hey! I would like to work on this.

**Comment by ggggg-15** [comment]
@shivprime94 Yeah sure! I have already taken the tag feature issue so you can take this up.

**Comment by ggggg-15** [comment]
@PrimalPimmy please assign this issue to @shivprime94 instead of me, I have been assigned another issue already. Thank you!

**Comment by osBins** [comment]
@shivprime94 can I have an update on this?
