### ISSUE TITLE
Online users list doesn't show the user itself but only other users

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#59]
Modify the online users list to show "<your username> (you)" in addition to other online users.

**Comment by saisumanthkumar** [comment]
@osBins I'd like to work on this

**Comment by osBins** [comment]
Great, assigning this issue to you @saisumanthkumar!

**Comment by vedantiitkgp** [comment]
I have already fixed this

**Comment by osBins** [comment]
@vedantiitkgp can you undo this particular change, (along with the timestamp one), since we have separate issues for these and people already working on them? Thank you for understanding!

**Comment by vedantiitkgp** [comment]
I was bound to fix this issue because I have to create some design changes accordingly it would create a mess if I fix this issue

**Comment by osBins** [comment]
I agree that this issue falls under your jurisdiction since it's related to design. However now that we already have someone working on it, it would be unfair to them if it's implemented by someone else. Could you create a Pull Request so that we could take a look at how undoing the specific changes might create a mess?
