### ISSUE TITLE
add emoji keyboard

### ISSUE THREAD

**Issue by kuldeepsingh0330** [osBins/chatApp#70]
![1](https://user-images.githubusercontent.com/95225751/144888209-3b49a7b4-c5d3-4548-968a-485cae70d70e.png)
like this......

**Comment by PrimalPimmy** [comment]
Hey @kuldeepsingh0330 , nice work on this, I'm assigning this issue to you. But don't make a PR just yet, we're doing some UI changes in #69  that you might have to rebase with your own fork, before implementing this. Other than that, it's a great feature :+1:
