### ISSUE TITLE
Fix empty space on right side in chatApp

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#71]
Horizontal scrollbar below shows a lot of empty space to the right. Empty space needs to be removed so that there's no horizontal bar and everything is perfectly centered on screen.
![image](https://user-images.githubusercontent.com/70942982/144973301-d3639ab3-ebb7-45ea-a2a4-3c824070f011.png)

**Comment by amm98d** [comment]
Hi @osBins, I would like to take this, if possible :)

**Comment by osBins** [comment]
Great! Assigning this to you @amm98d
