### ISSUE TITLE
Prevent HTML tags from being rendered in chat messages and show plain-text

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#77]
Currently, HTML tags like `<h1>, <b>` and others are rendered. They should be shown as plain-text instead of rendering. 
![image](https://user-images.githubusercontent.com/70942982/144991004-00559ccd-4e57-45b0-8eba-47685bd79fd5.png)

**Comment by saisumanthkumar** [comment]
@osBins I'd like to work on this

**Comment by osBins** [comment]
Great, you can club it with the markdown issue #76 and create a single PR for this.
