### ISSUE TITLE
Stylizing 'search' box

### ISSUE THREAD

**Issue by osBins** [osBins/chatApp#88]
The search box position is currently on the top left and it looks plain.
The position is to be fixed in a good spot on the page and stylized to make it look better.

**Comment by vedantiitkgp** [comment]
@osBins assign me

**Comment by osBins** [comment]
Great! Assigning this issue to you @vedantiitkgp.

**Comment by Bibhavshah** [comment]
Can I work on this issue?

**Comment by osBins** [comment]
Hey @Bibhavshah, this issue has already been resolved via #105. Feel free to go through the list of issues and work on one not assigned to anyone, or you could create an issue to work on for yourself too!
