### ISSUE TITLE
Stylizing the Online members Tab

### ISSUE THREAD

**Issue by RahulSharma4329** [osBins/chatApp#97]
fix alignment issue like this
![Screenshot from 2021-12-17 02-04-45](https://user-images.githubusercontent.com/74984914/146445844-58378da9-44b0-48ec-aee8-a466946bb0fd.png)

**Comment by RahulSharma4329** [comment]
i want to work on this please asign it to me

**Comment by osBins** [comment]
Good find for an issue @RahulSharma4329! Assigning this to you.
